language: node_js
node_js:
- stable
script:
- npx cypress run
branches:
  only: master
notifications:
  email:
    recipients:
    - joexu1997@gmail.com
    - joedream1997@egmail.com
    on_success: never
    on_failure: always
