dist: trusty
language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
install:
- npm ci
before_script:
- sudo npm install -g httpserver
- npm run custom-build
- cd dist && httpserver -p 8080 &
script:
- npx cypress run


